name: Dockerimage

on:
 workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      
      run: | 
        echo "${{ secrets.DOCKER_PW }}" |  docker login -u "sivavarmaboddu" --password-stdin 
        docker image build -t sivavarmaboddu/hello-app:latest ./hello-app
        docker push sivavarmaboddu/hello-app:latest
